{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "\n",
    "# hbar * c [GeV * fm]\n",
    "hbarc = 0.197326 \n",
    "\n",
    "# Simulation box \n",
    "L = 10      \n",
    "N = 512 \n",
    "tau_sim = 1.0     \n",
    "DTS = 8     \n",
    "\n",
    "# Glasma\n",
    "su_group = 'su3'\n",
    "# Qs = 1.4 \n",
    "Qs = 2.0     \n",
    "ns = 50      \n",
    "factor = 0.8        \n",
    "uv = 10.0 \n",
    "\n",
    "# Wong\n",
    "quark = 'charm'    \n",
    "mass = 1.275       \n",
    "\n",
    "# tau_form = 0\n",
    "initialization = 'pT'         \n",
    "ntp = 10**5  \n",
    "\n",
    "# nevents = 10   \n",
    "nevents = 10\n",
    "# npTbins = 100 \n",
    "# pTmax = 10\n",
    "\n",
    "# representation = 'quantum fundamental'     \n",
    "representation = 'fundamental' \n",
    "boundary = 'periodic'  \n",
    "\n",
    "# pTs = np.linspace(0, pTmax, npTbins)\n",
    "pTs = [0, 0.5, 1, 5]\n",
    "\n",
    "# Store relevant parameters in a dictionary\n",
    "p = {\n",
    "    'QUARK': quark,\n",
    "    'MASS': mass,   \n",
    "    'QS': Qs,            \n",
    "    'NEVENTS': nevents,\n",
    "    # 'NPTBINS': npTbins,   \n",
    "    'NTP': ntp,   \n",
    "    # 'PT': pTmax,   \n",
    "    'PTBINS': pTs,\n",
    "    }"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "# rest of parameters  \n",
    "g2mu = p[\"QS\"] / factor     \n",
    "g = np.pi * np.sqrt(1 / np.log(p[\"QS\"] / 0.2))          \t\t\n",
    "mu = g2mu / g**2          \t\n",
    "ir = 0.1 * g2mu     \n",
    "\n",
    "tau_form = 1/(2*p[\"MASS\"])*hbarc\n",
    "tau_sim += tau_form\n",
    "\n",
    "# Results folder\n",
    "# folder = 'RAA_' + p[\"QUARK\"] + '_fonll_Qs_' + str(p[\"QS\"]) + '_clcasimir'\n",
    "folder = 'RAA_' + p[\"QUARK\"] + '_fonll_Qs_' + str(p[\"QS\"]) + '_qmcasimir'\n",
    "filename = 'test_pTs_10_ev.pickle'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Using CUDA\n",
      "Using SU(3)\n",
      "Using double precision\n",
      "Using double precision\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "os.environ[\"MY_NUMBA_TARGET\"] = \"cuda\"\n",
    "os.environ[\"PRECISION\"] = \"double\"\n",
    "os.environ[\"GAUGE_GROUP\"] = su_group\n",
    "\n",
    "# Import relevant modules\n",
    "import sys\n",
    "sys.path.append('..')\n",
    "\n",
    "# Glasma modules\n",
    "import curraun.core as core\n",
    "import curraun.mv as mv\n",
    "import curraun.initial as initial\n",
    "initial.DEBUG = False\n",
    "\n",
    "import curraun.su as su\n",
    "from curraun.numba_target import use_cuda\n",
    "if use_cuda:\n",
    "    from numba import cuda\n",
    "\n",
    "# Wong modules\n",
    "from curraun import wong\n",
    "wong.BOUNDARY = boundary\n",
    "wong.WONG_TO_HOST = True\n",
    "from curraun.wong import init_pos, init_charge, init_mom_toy\n",
    "from curraun.particles_correlators import TransMom"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pickle\n",
    "from tqdm import tqdm\n",
    "\n",
    "current_path = os.getcwd() \n",
    "results_folder = 'results'\n",
    "if not os.path.isdir(results_folder):\n",
    "    os.makedirs(results_folder)\n",
    "results_path = current_path + '/' + results_folder + '/'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "def simulate(p): \n",
    "    os.chdir(results_path)\n",
    "\n",
    "    output = {}\n",
    "    output['parameters'] = p.copy()\n",
    "    output['pTs'] = p['PTBINS']\n",
    "    output['nevents'] = p[\"NEVENTS\"]\n",
    "\n",
    "    # Derived parameters\n",
    "    a = L/N\n",
    "    E0 = N/L * hbarc\n",
    "    DT = 1.0 / DTS\n",
    "    formt = int(tau_form / a * DTS)\n",
    "    maxt = int(tau_sim / a * DTS)\n",
    "\n",
    "    # Initialize Glasma fields\n",
    "    s = core.Simulation(N, DT, g)\n",
    "    va = mv.wilson(s, mu=mu / E0, m=ir / E0, uv=uv / E0, num_sheets=ns)\n",
    "    vb = mv.wilson(s, mu=mu / E0, m=ir / E0, uv=uv / E0, num_sheets=ns)\n",
    "    initial.init(s, va, vb)\n",
    "\n",
    "    for ipT, pT in enumerate(p['PTBINS']):\n",
    "        print(\"pT = \" + str(pT) + \" GeV\")\n",
    "\n",
    "        output[str(pT)] = {}\n",
    "        \n",
    "        for ev in range(0, p[\"NEVENTS\"]):\n",
    "            # Initialize the Wong solver\n",
    "            wong_solver = wong.WongSolver(s, ntp)\n",
    "            x0s, p0s, q0s = np.zeros((ntp, 3)), np.zeros((ntp, 5)), np.zeros((ntp, su.ALGEBRA_ELEMENTS))\n",
    "            masses = p[\"MASS\"] / E0 * np.ones(ntp)\n",
    "\n",
    "            for i in range(ntp):\n",
    "                x0, p0, q0 = init_pos(s.n), init_mom_toy('pT', pT / E0), init_charge(representation)\n",
    "                x0s[i, :], p0s[i, :], q0s[i, :] = x0, p0, q0\n",
    "            \n",
    "            wong_solver.initialize(x0s, p0s, q0s, masses)\n",
    "\n",
    "            pTs = np.zeros((maxt-formt, ntp))\n",
    "            compute_pT = TransMom(wong_solver, ntp)\n",
    "\n",
    "            with tqdm(total=maxt) as pbar:\n",
    "                for t in range(maxt):\n",
    "                    # Evolve Glasma fields\n",
    "                    core.evolve_leapfrog(s)\n",
    "\n",
    "                    # Solve Wong's equations\n",
    "                    if t>=formt:  \n",
    "                        compute_pT.compute()\n",
    "                        pTs[t-formt] = compute_pT.pT.copy() * E0\n",
    "                        \n",
    "                        wong_solver.evolve()\n",
    "\n",
    "                    pbar.set_description(\"Event \" + str(ev+1))\n",
    "                    pbar.update(1)\n",
    "\n",
    "            output[str(pT)]['pTs_event_'+ str(ev+1)] = pTs\n",
    "\n",
    "    tau = np.linspace(0, tau_sim-tau_form, maxt-formt)\n",
    "    output['tau'] = tau\n",
    "\n",
    "    wong_folder = folder\n",
    "    if not os.path.isdir(wong_folder):\n",
    "        os.makedirs(wong_folder)\n",
    "    wong_path = results_path + '/' + wong_folder + '/'\n",
    "    os.chdir(wong_path)\n",
    "\n",
    "    with open(filename, 'wb') as handle:\n",
    "        pickle.dump(output, handle)\n",
    "    return output"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Charm quark\n",
      "pT = 0 GeV\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Event 1: 100%|██████████| 441/441 [01:58<00:00,  3.72it/s]\n",
      "Event 2: 100%|██████████| 441/441 [01:45<00:00,  4.19it/s]\n",
      "Event 3: 100%|██████████| 441/441 [01:46<00:00,  4.15it/s]\n",
      "Event 4: 100%|██████████| 441/441 [01:45<00:00,  4.17it/s]\n",
      "Event 5: 100%|██████████| 441/441 [01:45<00:00,  4.17it/s]\n",
      "Event 6: 100%|██████████| 441/441 [01:45<00:00,  4.17it/s]\n",
      "Event 7: 100%|██████████| 441/441 [01:45<00:00,  4.19it/s]\n",
      "Event 8: 100%|██████████| 441/441 [01:45<00:00,  4.20it/s]\n",
      "Event 9: 100%|██████████| 441/441 [01:45<00:00,  4.19it/s]\n",
      "Event 10: 100%|██████████| 441/441 [01:45<00:00,  4.18it/s]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "pT = 0.5 GeV\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Event 1: 100%|██████████| 441/441 [02:02<00:00,  3.60it/s]\n",
      "Event 2: 100%|██████████| 441/441 [01:54<00:00,  3.86it/s]\n",
      "Event 3: 100%|██████████| 441/441 [01:46<00:00,  4.16it/s]\n",
      "Event 4: 100%|██████████| 441/441 [01:45<00:00,  4.18it/s]\n",
      "Event 5: 100%|██████████| 441/441 [01:45<00:00,  4.17it/s]\n",
      "Event 6: 100%|██████████| 441/441 [01:45<00:00,  4.17it/s]\n",
      "Event 7: 100%|██████████| 441/441 [01:46<00:00,  4.16it/s]\n",
      "Event 8: 100%|██████████| 441/441 [01:45<00:00,  4.17it/s]\n",
      "Event 9: 100%|██████████| 441/441 [01:45<00:00,  4.16it/s]\n",
      "Event 10: 100%|██████████| 441/441 [01:46<00:00,  4.14it/s]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "pT = 1 GeV\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Event 1: 100%|██████████| 441/441 [01:45<00:00,  4.16it/s]\n",
      "Event 2: 100%|██████████| 441/441 [01:45<00:00,  4.17it/s]\n",
      "Event 3: 100%|██████████| 441/441 [01:46<00:00,  4.15it/s]\n",
      "Event 4: 100%|██████████| 441/441 [01:47<00:00,  4.08it/s]\n",
      "Event 5: 100%|██████████| 441/441 [01:46<00:00,  4.12it/s]\n",
      "Event 6: 100%|██████████| 441/441 [01:51<00:00,  3.94it/s]\n",
      "Event 7: 100%|██████████| 441/441 [01:48<00:00,  4.06it/s]\n",
      "Event 8: 100%|██████████| 441/441 [01:49<00:00,  4.01it/s]\n",
      "Event 9: 100%|██████████| 441/441 [01:47<00:00,  4.08it/s]\n",
      "Event 10: 100%|██████████| 441/441 [01:55<00:00,  3.83it/s]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "pT = 5 GeV\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Event 1: 100%|██████████| 441/441 [01:52<00:00,  3.94it/s]\n",
      "Event 2: 100%|██████████| 441/441 [01:48<00:00,  4.06it/s]\n",
      "Event 3: 100%|██████████| 441/441 [01:52<00:00,  3.91it/s]\n",
      "Event 4: 100%|██████████| 441/441 [01:48<00:00,  4.08it/s]\n",
      "Event 5: 100%|██████████| 441/441 [01:47<00:00,  4.09it/s]\n",
      "Event 6: 100%|██████████| 441/441 [01:48<00:00,  4.05it/s]\n",
      "Event 7: 100%|██████████| 441/441 [01:47<00:00,  4.10it/s]\n",
      "Event 8: 100%|██████████| 441/441 [01:47<00:00,  4.12it/s]\n",
      "Event 9: 100%|██████████| 441/441 [01:47<00:00,  4.10it/s]\n",
      "Event 10: 100%|██████████| 441/441 [01:49<00:00,  4.04it/s]\n"
     ]
    }
   ],
   "source": [
    "print(p['QUARK'].capitalize() + \" quark\")\n",
    "\n",
    "output = simulate(p)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [],
   "source": [
    "# from old version, should be rewritten\n",
    "pTs_tau = output['0.5']['pTs_event_1'][1, :]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3343, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-15-deb65a2d8b7e>\", line 1, in <module>\n",
      "    import matplotlib.pyplot as plt\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/site-packages/matplotlib/__init__.py\", line 921, in <module>\n",
      "    dict.update(rcParams, _rc_params_in_file(matplotlib_fname()))\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/site-packages/matplotlib/__init__.py\", line 602, in matplotlib_fname\n",
      "    for fname in gen_candidates():\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/site-packages/matplotlib/__init__.py\", line 591, in gen_candidates\n",
      "    yield os.path.join(os.getcwd(), 'matplotlibrc')\n",
      "FileNotFoundError: [Errno 2] No such file or directory\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'FileNotFoundError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1169, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/inspect.py\", line 1490, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/inspect.py\", line 1448, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/inspect.py\", line 725, in getmodule\n",
      "    file = getabsfile(object, _filename)\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/inspect.py\", line 709, in getabsfile\n",
      "    return os.path.normcase(os.path.abspath(_filename))\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/posixpath.py\", line 383, in abspath\n",
      "    cwd = os.getcwd()\n",
      "FileNotFoundError: [Errno 2] No such file or directory\n",
      "Traceback (most recent call last):\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3343, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-15-deb65a2d8b7e>\", line 1, in <module>\n",
      "    import matplotlib.pyplot as plt\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/site-packages/matplotlib/__init__.py\", line 921, in <module>\n",
      "    dict.update(rcParams, _rc_params_in_file(matplotlib_fname()))\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/site-packages/matplotlib/__init__.py\", line 602, in matplotlib_fname\n",
      "    for fname in gen_candidates():\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/site-packages/matplotlib/__init__.py\", line 591, in gen_candidates\n",
      "    yield os.path.join(os.getcwd(), 'matplotlibrc')\n",
      "FileNotFoundError: [Errno 2] No such file or directory\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'FileNotFoundError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3263, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3360, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2047, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1436, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1336, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1193, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1169, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/inspect.py\", line 1490, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/inspect.py\", line 1448, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/inspect.py\", line 725, in getmodule\n",
      "    file = getabsfile(object, _filename)\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/inspect.py\", line 709, in getabsfile\n",
      "    return os.path.normcase(os.path.abspath(_filename))\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/posixpath.py\", line 383, in abspath\n",
      "    cwd = os.getcwd()\n",
      "FileNotFoundError: [Errno 2] No such file or directory\n",
      "Traceback (most recent call last):\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3343, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-15-deb65a2d8b7e>\", line 1, in <module>\n",
      "    import matplotlib.pyplot as plt\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/site-packages/matplotlib/__init__.py\", line 921, in <module>\n",
      "    dict.update(rcParams, _rc_params_in_file(matplotlib_fname()))\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/site-packages/matplotlib/__init__.py\", line 602, in matplotlib_fname\n",
      "    for fname in gen_candidates():\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/site-packages/matplotlib/__init__.py\", line 591, in gen_candidates\n",
      "    yield os.path.join(os.getcwd(), 'matplotlibrc')\n",
      "FileNotFoundError: [Errno 2] No such file or directory\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'FileNotFoundError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3263, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3360, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2047, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1436, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1336, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1193, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2895, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3072, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3282, in run_ast_nodes\n",
      "    self.showtraceback()\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2047, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1436, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1336, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1211, in structured_traceback\n",
      "    chained_exceptions_tb_offset)\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1169, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/inspect.py\", line 1490, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/inspect.py\", line 1448, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/inspect.py\", line 725, in getmodule\n",
      "    file = getabsfile(object, _filename)\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/inspect.py\", line 709, in getabsfile\n",
      "    return os.path.normcase(os.path.abspath(_filename))\n",
      "  File \"/n/work00/davrames/condacurraun/lib/python3.6/posixpath.py\", line 383, in abspath\n",
      "    cwd = os.getcwd()\n",
      "FileNotFoundError: [Errno 2] No such file or directory\n"
     ]
    }
   ],
   "source": [
    "import matplotlib.pyplot as plt\n",
    "from scipy import stats\n",
    "\n",
    "fig, axes = plt.subplots(nrows=1, ncols=1)\n",
    "\n",
    "pT_bins = np.linspace(np.min(pTs_tau), np.max(pTs_tau), 100)\n",
    "density = stats.kde.gaussian_kde(pTs_tau)\n",
    "axes.plot(pT_bins, density(pT_bins))"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.8"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
